version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - pod-monitor
  pod-monitor:
    build: .
    volumes:
      - ./clusters:/app/clusters
      - ./data:/app/data
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    command: python backend/api.py
