version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./clusters:/app/clusters
      - ./data:/app/data
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    command: python backend/api.py

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - VITE_API_URL=http://localhost:8000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
